// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type InsertAccountArgs = {
  readonly "id": string;
  readonly "address": string;
  readonly "name": string;
  readonly "implementation": string;
  readonly "initialization": {
    readonly "salt": string;
    readonly "bytecodeHash": string;
    readonly "aaVersion": number;
  };
};

export type InsertAccountReturns = {
  "id": string;
};

export function insertAccount(client: Executor, args: InsertAccountArgs): Promise<InsertAccountReturns> {
  return client.queryRequiredSingle(`\
insert Account {
  id := <uuid>$id,
  address := <UAddress>$address,
  name := <str>$name,
  implementation := <Address>$implementation,
  initialization := <tuple<salt: Bytes32, bytecodeHash: Bytes32, aaVersion: uint16>>$initialization
}`, args);

}
