// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type InsertAccountArgs = {
  readonly "id": string;
  readonly "address": string;
  readonly "name": string;
  readonly "implementation": string;
  readonly "salt": string;
};

export type InsertAccountReturns = {
  "id": string;
};

export function insertAccount(client: Executor, args: InsertAccountArgs): Promise<InsertAccountReturns> {
  return client.queryRequiredSingle(`\
insert Account {
  id := <uuid>$id,
  address := <UAddress>$address,
  name := <str>$name,
  implementation := <Address>$implementation,
  salt := <Bytes32>$salt
}`, args);

}
