// GENERATED by @edgedb/generate v0.5.3

import type { Executor } from 'edgedb';

export type DeleteTransactionArgs = {
  readonly transaction: string;
};

export type DeleteTransactionReturns = {
  transaction: {
    id: string;
    account: {
      address: string;
    };
  } | null;
  deletedPolicies: Array<{
    id: string;
  }>;
  deletedTransaction: {
    id: string;
  } | null;
};

export function deleteTransaction(
  client: Executor,
  args: DeleteTransactionArgs,
): Promise<DeleteTransactionReturns> {
  return client.queryRequiredSingle(
    `\
with t := (select Transaction filter .id = <uuid>$transaction)
select {
  transaction := (
    select t {
      id,
      account: { address }
    }
  ),
  deletedPolicies := (delete t.<proposal[is PolicyState]),
  deletedTransaction := (delete t)
};`,
    args,
  );
}
