// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type InsertSystxArgs = {
  readonly "hash": string;
  readonly "proposal": string;
  readonly "maxEthFeePerGas": string;
  readonly "ethPerFeeToken": string;
  readonly "usdPerFeeToken": string;
};

export type InsertSystxReturns = {
  "id": string;
};

export function insertSystx(client: Executor, args: InsertSystxArgs): Promise<InsertSystxReturns> {
  return client.queryRequiredSingle(`\
insert SystemTx {
  hash := <Bytes32>$hash,
  proposal := (select Transaction filter .id = <uuid>$proposal),
  maxEthFeePerGas := <decimal>$maxEthFeePerGas,
  ethPerFeeToken := <decimal>$ethPerFeeToken,
  usdPerFeeToken := <decimal>$usdPerFeeToken
}`, args);

}
