// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type UpdatePaymasterFeesArgs = {
  readonly "activation": string;
  readonly "transaction": string;
};

export type UpdatePaymasterFeesReturns = {
  "id": string;
} | null;

export function updatePaymasterFees(client: Executor, args: UpdatePaymasterFeesArgs): Promise<UpdatePaymasterFeesReturns> {
  return client.querySingle(`\
update Transaction
filter .id = <uuid>$transaction
set {
  paymasterEthFees := (
    insert PaymasterFees {
      activation := <decimal>$activation,
    }
  )
}`, args);

}
