// https://github.com/facebook/relay/tree/main/packages/relay-compiler#configuration
module.exports = {
  src: './src',
  schema: '../api/schema.graphql',
  language: 'typescript',
  excludes: [
    '**/node_modules/**',
    '**/__mocks__/**',
    '**/__generated__/**',
    'relay.config.js',
    'babel.config.js',
  ],
  artifactDirectory: './src/api/__generated__',
  schemaExtensions: ['./src/api/local'],
  customScalarTypes: {
    // ID: { name: 'UUID', path: 'lib' },
    Address: { name: 'Address', path: 'lib' },
    UAddress: { name: 'UAddress', path: 'lib' },
    BigInt: 'string',
    Bytes: { name: 'Hex', path: 'lib' },
    Bytes32: { name: 'Hex', path: 'lib' },
    Chain: { name: 'Chain', path: 'chains' },
    DateTime: 'string',
    Decimal: { name: 'Decimallike', path: 'lib' },
    MAC: 'string',
    PolicyKey: { name: 'PolicyKey', path: 'lib' },
    Selector: { name: 'Selector', path: 'lib' },
    Uint256: 'string',
    UUID: { name: 'UUID', path: 'lib' },
    URL: 'string',
    TypedData: { name: 'TypedDataDefinition', path: 'viem' },
    AbiFunction: { name: 'AbiFunction', path: 'abitype' },
  },
};
