// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type DeleteResponseArgs = {
  readonly "proposal": string;
  readonly "approver": string;
};

export type DeleteResponseReturns = {
  "id": string;
} | null;

export function deleteResponse(client: Executor, args: DeleteResponseArgs): Promise<DeleteResponseReturns> {
  return client.querySingle(`\
with proposal := (select Proposal filter .id = <uuid>$proposal),
     approver := (select Approver filter .address = <Address>$approver)
delete ProposalResponse filter .proposal = proposal and .approver = approver`, args);

}
