// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type RejectProposalArgs = {
  readonly "proposal": string;
};

export type RejectProposalReturns = {
  "id": string;
};

export function rejectProposal(client: Executor, args: RejectProposalArgs): Promise<RejectProposalReturns> {
  return client.queryRequiredSingle(`\
with proposal := (select Proposal filter .id = <uuid>$proposal),
     deletedResponse := (delete ProposalResponse filter .proposal = proposal and .approver = global current_approver)
insert Rejection {
  proposal := proposal
}`, args);

}
