// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type RejectProposalArgs = {
  readonly "proposal": string;
  readonly "approver": string;
};

export type RejectProposalReturns = {
  "rejection": string;
  "proposal": {
    "id": string;
    "account": {
      "address": string;
    };
  } | null;
};

export function rejectProposal(client: Executor, args: RejectProposalArgs): Promise<RejectProposalReturns> {
  return client.queryRequiredSingle(`\
with proposal := (select Proposal filter .id = <uuid>$proposal),
     approver := (select Approver filter .address = <Address>$approver)
    #  deletedResponse := (delete ProposalResponse filter .proposal = proposal and .approver = approver)
select {
  rejection := (
    insert Rejection { 
      proposal := proposal,
      approver := approver
    }
  ).id,
  proposal := (
    id := proposal.id,
    account := { address := proposal.account.address }
  )
}`, args);

}
