// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type InsertSimulationArgs = {
  readonly "transaction": string;
  readonly "transfers": ReadonlyArray<unknown>;
  readonly "executable": boolean;
  readonly "success": boolean;
  readonly "responses": ReadonlyArray<string>;
};

export type InsertSimulationReturns = {
  "prevSimulation": {
    "id": string;
  } | null;
  "tx": {
    "id": string;
  } | null;
};

export function insertSimulation(client: Executor, args: InsertSimulationArgs): Promise<InsertSimulationReturns> {
  return client.queryRequiredSingle(`\
with tx := (select Transaction filter .id = <uuid>$transaction),
     transfers := <array<json>>$transfers,
     account := tx.account
select {
  prevSimulation := (delete tx.simulation),
  tx := (
    update tx set {
      executable := <bool>$executable,
      simulation := (insert Simulation {
        success := <bool>$success,
        responses := <array<Bytes>>$responses,
        transfers := assert_distinct((
          for transfer in array_unpack(transfers) union ( 
            insert TransferDetails {
              account := account,
              from := <Address>transfer['from'],
              to := <Address>transfer['to'],
              tokenAddress := <UAddress>transfer['tokenAddress'],
              amount := <decimal><str>transfer['amount'],
              incoming := <bool>transfer['incoming'],
              outgoing := <bool>transfer['outgoing']
            }
          ) if count(transfers) > 0 else {}
        ))
      })
    }
  )
}`, args);

}
