// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type InsertSimulatedSuccessArgs = {
  readonly "transaction": string;
  readonly "response": string;
  readonly "gasUsed": bigint;
};

export type InsertSimulatedSuccessReturns = {
  "id": string;
};

export function insertSimulatedSuccess(client: Executor, args: InsertSimulatedSuccessArgs): Promise<InsertSimulatedSuccessReturns> {
  return client.queryRequiredSingle(`\
insert SimulatedSuccess {
  transaction := <Transaction><uuid>$transaction,
  response := <Bytes>$response,
  gasUsed := <bigint>$gasUsed
}`, args);

}
