// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type UpdatePolicyDetailsArgs = {
  readonly "account": string;
  readonly "key": number;
  readonly "name": string;
};

export type UpdatePolicyDetailsReturns = Array<{
  "id": string;
}>;

export function updatePolicyDetails(client: Executor, args: UpdatePolicyDetailsArgs): Promise<UpdatePolicyDetailsReturns> {
  return client.query(`\
with account := (select Account filter .address = <UAddress>$account),
     latest := (select Policy filter .account = account and .key = <uint16>$key and .isLatest)
update (latest union latest.draft[is Policy]) set {
  name := <str>$name
}`, args);

}
